// const { Router } = require("express");
// const PropertyModel = require("../models/PropertyModel.js");
const { Router } = require("express");
const PropertyModel = require("../models/PropertyModel.js");
const { ObjectId } = require("mongodb");
const getFilterObj = require("../utiles/getFilterObj.js");

const propertyRouter = Router();

propertyRouter.get("/", async (req, res) => {
  try {
    const query = req.query;
    // console.log(query);

    // Getting the filter object for database query
    const filter = getFilterObj(query);

    // Controlling pagination
    const itemsPerPage = 10;

    let skipCount = 0;
    if (query.selectedPage) {
      skipCount = (query.selectedPage - 1) * itemsPerPage;
    }
    // const properties = await PropertyModel.find(filter)
    //   .skip(skipCount)
    //   .limit(itemsPerPage);

    return res.send([
      {
        _id: "672c1945473342b86ffdb741",
        AGENT_REF: "115_28r",
        ADDRESS_1: "12",
        ADDRESS_2: "Delph Lane",
        ADDRESS_3: "Woodhouse",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "2HQ",
        FEATURE1: "EPC-E",
        FEATURE2: "Great price",
        FEATURE3: "Separate Living Room",
        FEATURE4: "Equal size bedrooms",
        FEATURE5: "&pound;0.00 PPPW",
        FEATURE6: "17/08/2024",
        FEATURE7: "Close to UNI",
        FEATURE8: "",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " Four bedroom house in Woodhouse. *Great location* *Great value for rental!* * &pound;102.00PPPW* *17/08/2024*",
        DESCRIPTION:
          " Four bedroom house in Woodhouse.  *Large Bedrooms**No ground floor Bedrooms**Close to City* * &pound;102.00PPPW* *17/08/2024* This 4 bedroom property has large bedrooms, a cosy living room and a separate kitchen. There is a house bathroom on the middle floor which has a bath/shower, and a toilet. The property is modern throughout with laminate flooring and bright spacious rooms. This property is located on the edge of Woodhouse, right by TJ&apos;s Bar and Grill and perfect for students who are looking for a short walk to University and the city centre.",
        BRANCH_ID: "115",
        STATUS_ID: "0",
        BEDROOMS: "4",
        BATHROOMS: "1",
        LIVING_ROOMS: "1",
        PRICE: "102",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Delph Lane, Woodhouse, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2024-08-17",
        LET_BOND: "250",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "N",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000028_0018.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000028_0011.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000028_0012.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000028_0013.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000028_0014.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000028_0015.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000028_0016.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000028_0017.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_28_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "2",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "51",
        EPC_EERP: "81",
        EPC_EIR: "43",
        EPC_EIRP: "77",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb742",
        AGENT_REF: "115_68r",
        ADDRESS_1: "19",
        ADDRESS_2: "Lucas Street",
        ADDRESS_3: "Woodhouse",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "2JD",
        FEATURE1: "2 Bathrooms",
        FEATURE2: "Separate Living Room",
        FEATURE3: "Double Beds",
        FEATURE4: "#weeklyrent# PPPW",
        FEATURE5: "Central location",
        FEATURE6: "01/07/2025",
        FEATURE7: "Modern",
        FEATURE8: "",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " Modern four bedroom property. *Close to City centre Universities* *Modern decor* *Large communal space* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          "Modern four bedroom property. *Close to City centre Universities* *Modern decor* *Large communal space* * &pound;0.00PPPW* *01/07/2025* The property briefly comprises of four double bedrooms, a large kitchen with dining table, and a homely living room, as well as a 2 house bathrooms. The house is perfect for sociable groups who enjoy spend a lot of time in the communal areas and want to be a very short walk from the City centre Universities. Woodhouse is the closest district to both The University of Leeds and Leeds Beckett University city centre campus and for this reason has become one of the most requested areas for students accommodation. It has several convenience stores, TJ&apos;s Bar and if your looking for a sweet treat then we definitely recommend Whitley&apos;s bakery!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "4",
        BATHROOMS: "1",
        LIVING_ROOMS: "1",
        PRICE: "87",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Lucas Street, Woodhouse, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "250",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000068_0022.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000068_0017.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000068_0018.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000068_0019.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000068_0020.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000068_0021.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000068_0023.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000068_0024.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000068_0025.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_68_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "2",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "54",
        EPC_EERP: "81",
        EPC_EIR: "45",
        EPC_EIRP: "77",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb743",
        AGENT_REF: "115_94r",
        ADDRESS_1: "215",
        ADDRESS_2: "Woodhouse Street",
        ADDRESS_3: "Woodhouse",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "2NY",
        FEATURE1: "#weeklyrent# pppw",
        FEATURE2: "EPC-D",
        FEATURE3: "Five equal sized bedrooms",
        FEATURE4: "Large living area",
        FEATURE5: "Two bathrooms",
        FEATURE6: "Bath and showers",
        FEATURE7: "Dining kitchen",
        FEATURE8: "01/07/2025",
        FEATURE9: "Dishwasher and dryer!",
        FEATURE10: "",
        SUMMARY:
          " Wonderfully presented five bedroom property as well as being a very short walk to the City Centre *Modern finish* *Two bathrooms**Equal size bedrooms* *Large living room* *Great Location* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          " Wonderfully presented five bedroom property as well as being a very short walk to the City Centre  *Modern finish* *Two bathrooms**Equal size bedrooms* *Large living room* *Great Location* * &pound;0.00PPPW* *01/07/2025* The property briefly comprises of five equal size bedrooms with double beds and modern furniture, a large living room and a modern dining kitchen with white goods, as well as two bathrooms with a bath and shower. A great location less than a two minute walk from the university and within walking distance to the city centre. Woodhouse is the closest district to both The University of Leeds and Leeds Beckett University city centre campus and for this reason has become one of the most requested areas for students accommodation. It has several convenience stores, TJ&apos;s Bar and if your looking for a sweet treat then we definitely recommend Whitley&apos;s bakery!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "5",
        BATHROOMS: "2",
        LIVING_ROOMS: "1",
        PRICE: "97",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Woodhouse Street, Woodhouse, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "300",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "Y",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000094_0018.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000094_0015.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000094_0009.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000094_0010.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000094_0011.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000094_0012.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000094_0013.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000094_0014.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000094_0016.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "p000094_0017.jpg",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_94_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "63",
        EPC_EERP: "85",
        EPC_EIR: "55",
        EPC_EIRP: "82",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb744",
        AGENT_REF: "115_161r",
        ADDRESS_1: "7",
        ADDRESS_2: "Ashville Avenue",
        ADDRESS_3: "Hyde Park",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "1LX",
        FEATURE1: "EPC-D",
        FEATURE2: "#weeklyrent# pppw",
        FEATURE3: "Separate Living Room",
        FEATURE4: "Double Beds",
        FEATURE5: "01/07/2025",
        FEATURE6: "Double Glazed",
        FEATURE7: "En-suites",
        FEATURE8: "Close to UNI",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " This well presented six bedroom property in central Hyde Park *Equal size en-suite bedrooms* *Large living room* *TV`s in every room* *Dishwasher and dryer* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          " This well presented six bedroom property in central Hyde Park  *Equal size en-suite bedrooms* *Large living room* *TV&apos;s in every room* *Dishwasher and dryer* * &pound;0.00PPPW* *01/07/2025* The property briefly comprises of 6 equal size double bedrooms with modern furniture, wall mounted TV&apos;s and en-suite shower rooms. The house also has a large living space with dining table and flat screen TV, a modern kitchen with dishwasher and dryer. As well as en-suites in every room there is a additional house bathroom.  Hyde Park has the largest student population in Leeds as it is a short walk to both The University of Leeds and Leeds Beckett University city centre campus as well as many other institution&apos;s including Leeds College of Art and Design. It has several convenience stores, a continental supermarket, a picture house, bars and pubs including the legendary Brudenell Social club. On a warm day its residents flood to Woodhouse Moor to enjoy the sun!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "6",
        BATHROOMS: "6",
        LIVING_ROOMS: "1",
        PRICE: "110",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Ashville Avenue, Hyde Park, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "300",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "N",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000161_0013.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000161_0002.jpg",
        MEDIA_IMAGE_TEXT_02: "bedroom 1",
        MEDIA_IMAGE_03: "p000161_0003.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000161_0004.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000161_0005.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000161_0006.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000161_0007.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000161_0008.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000161_0009.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "p000161_0010.jpg",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "p000161_0011.jpg",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "p000161_0012.jpg",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_161_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "60",
        EPC_EERP: "83",
        EPC_EIR: "51",
        EPC_EIRP: "79",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb745",
        AGENT_REF: "115_176r",
        ADDRESS_1: "5",
        ADDRESS_2: "Brudenell Mount",
        ADDRESS_3: "Hyde Park",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "1HS",
        FEATURE1: "EPC-E",
        FEATURE2: "Central Hyde park",
        FEATURE3: "Separate Living Room",
        FEATURE4: "Double Beds",
        FEATURE5: "#weeklyrent# PPPW",
        FEATURE6: "01/07/2025",
        FEATURE7: "TV included",
        FEATURE8: "Modern",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " This is a wonderfully presented six bedroom property in the heart of Hyde Park. *Large living area* *Amazing location* *TV`s in every room* *3 Bathrooms* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          " This is a wonderfully presented six bedroom property in the heart of Hyde Park.  *Large living area* *Amazing location* *TV&apos;s in every room* *3 Bathrooms* * &pound;0.00PPPW* *01/07/2025* The property briefly comprises of six double bedrooms some with en-suite and all with a TV, a large modern kitchen with dishwasher, washer and dryer. a huge living room to the front of the house with a large bay window and a large wall mounted TV. The house is modern throughout with 3 bathrooms with some bedrooms sharking a jack and jill bathroom. Hyde Park has the largest student population in Leeds as it is a short walk to both The University of Leeds and Leeds Beckett University city centre campus as well as many other institution&apos;s including Leeds College of Art and Design. It has several convenience stores, a continental supermarket, a picture house, bars and pubs including the legendary Brudenell Social club. On a warm day its residents flood to Woodhouse Moor to enjoy the sun!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "6",
        BATHROOMS: "4",
        LIVING_ROOMS: "1",
        PRICE: "116.5",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Brudenell Mount, Hyde Park, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "300",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "N",
        LET_DISHWASHER_FLAG: "Y",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000176_0006.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000176_0007.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000176_0008.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000176_0010.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000176_0011.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000176_0012.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000176_0004.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000176_0013.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000176_0014.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "p000176_0015.jpg",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "p000176_0016.jpg",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_176_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "42",
        EPC_EERP: "56",
        EPC_EIR: "37",
        EPC_EIRP: "49",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb746",
        AGENT_REF: "115_185r",
        ADDRESS_1: "145",
        ADDRESS_2: "St Michaels Lane",
        ADDRESS_3: "Burley",
        TOWN: "Leeds",
        POSTCODE1: "LS4",
        POSTCODE2: "2PD",
        FEATURE1: "Open plan kitchen and living area",
        FEATURE2: "EPC-D",
        FEATURE3: "Big Equal size bedrooms",
        FEATURE4: "Bath and shower",
        FEATURE5: "Modern decor throughout",
        FEATURE6: "On street parking",
        FEATURE7: "01/07/2025",
        FEATURE8: "#weeklyrent# PPPW BILLS INCLUDED",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " Wonderfully presented three bedroom property. *Modern Decor* *Spacious* *Open Plan Living**Bills included* *King size beds* * &pound;0.00PPPW* *01/07/2025* ",
        DESCRIPTION:
          " Wonderfully presented three bedroom property.  *Modern Decor* *Spacious* *Open Plan Living**Bills included* *King size beds* * &pound;0.00PPPW* *01/07/2025* Bills included - gas, water, electric, internet, TV licence and TV included. A spacious house spread over 4 floors, each bedroom has their own floor and the lounge and kitchen occupy the ground floor. An ideal house for those who want lots of space. The owner is a member of the Unipol Code. A MUST SEE! Burley is popular with students, post graduates and professionals alike. It is a short commute to both Leeds and Headingley campus and had great links to the City Centre including being along several bus routes. It also has its own train station, Burley Park Station which provides additional access to the city and also into Horsforth, so ideal for students studying at Trinity and All Saints University. Burley has many convenience stores and is a stones throw away from many restaurants, a cinema and for the healthiest among us several gyms!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "3",
        BATHROOMS: "1",
        LIVING_ROOMS: "1",
        PRICE: "140",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "3",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "St Michaels Lane, Burley, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "400",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "Y",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "Y",
        LET_BILL_INC_GAS: "Y",
        LET_BILL_INC_ELECTRICITY: "Y",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "Y",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000185_0007.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000185_0006.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000185_0008.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000185_0009.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000185_0011.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000185_0012.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000185_0013.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_185_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "58",
        EPC_EERP: "84",
        EPC_EIR: "51",
        EPC_EIRP: "81",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb747",
        AGENT_REF: "115_210r",
        ADDRESS_1: "45",
        ADDRESS_2: "Thornville Road",
        ADDRESS_3: "Hyde Park",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "1JY",
        FEATURE1: "",
        FEATURE2: "",
        FEATURE3: "",
        FEATURE4: "",
        FEATURE5: "",
        FEATURE6: "",
        FEATURE7: "",
        FEATURE8: "",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          "Good sized property, laminated throughout. Alarmed, good sized rooms, near mosque on Brudenell road.",
        DESCRIPTION:
          "Good sized property, laminated throughout. Alarmed, good sized rooms, near mosque on Brudenell road.",
        BRANCH_ID: "115",
        STATUS_ID: "0",
        BEDROOMS: "6",
        BATHROOMS: "1",
        LIVING_ROOMS: "1",
        PRICE: "85",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Thornville Road, Hyde Park, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2024-08-17",
        LET_BOND: "250",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000210_0001.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000210_0002.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000210_0003.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000210_0004.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000210_0005.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000210_0006.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000210_0007.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000210_0008.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000210_0009.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "p000210_0010.jpg",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "",
        MEDIA_IMAGE_TEXT_60: "",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "0",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "65",
        EPC_EERP: "75",
        EPC_EIR: "58",
        EPC_EIRP: "71",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb749",
        AGENT_REF: "115_250r",
        ADDRESS_1: "7",
        ADDRESS_2: "Norwood Terrace",
        ADDRESS_3: "Hyde Park",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "1EA",
        FEATURE1: "EPC-E",
        FEATURE2: "Bills included",
        FEATURE3: "Large Living Room",
        FEATURE4: "Modern Decor Throughout",
        FEATURE5: "Good Size Bedrooms",
        FEATURE6: "Gas Central Heating",
        FEATURE7: "Double Glazed",
        FEATURE8: "Two Bathrooms",
        FEATURE9: "Additional Toilet",
        FEATURE10: "&pound;0.00 PPPW",
        SUMMARY:
          " Wonderfully presented six bedroom property in the heart of Hyde Park. *Recently refurbished* *Large living room* *Modern decor* ",
        DESCRIPTION:
          " Wonderfully presented six bedroom property in the heart of Hyde Park. *Recently refurbished* *Large living room* *Modern decor*    The property comprises of six bright double bedrooms, kitchen with white goods, 2 house bathrooms and a large living room with a dining table. The landlord continues to improve the property recently adding new furniture, sofas and a TV. Hyde Park has the largest student population in Leeds as it is a short walk to both The University of Leeds and Leeds Beckett University city centre campus as well as many other institution&apos;s including Leeds College of Art and Design. It has several convenience stores, a continental supermarket, a picture house, bars and pubs including the legendary Brudenell Social club. On a warm day its residents flood to Woodhouse Moor to enjoy the sun!",
        BRANCH_ID: "115",
        STATUS_ID: "0",
        BEDROOMS: "5",
        BATHROOMS: "2",
        LIVING_ROOMS: "1",
        PRICE: "99.5",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Norwood Terrace, Hyde Park, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2024-08-17",
        LET_BOND: "300",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000250_0026.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000250_0033.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000250_0025.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000250_0027.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000250_0022.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000250_0032.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000250_0023.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000250_0031.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "p000250_0035.jpg",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "p000250_0029.jpg",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "p000250_0034.jpg",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "p000250_0028.jpg",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_250_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "48",
        EPC_EERP: "59",
        EPC_EIR: "42",
        EPC_EIRP: "53",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb74a",
        AGENT_REF: "115_293r",
        ADDRESS_1: "23",
        ADDRESS_2: "Providence Avenue",
        ADDRESS_3: "Woodhouse",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "2HN",
        FEATURE1: "EPC-E",
        FEATURE2: "Open plan living",
        FEATURE3: "Equal size bedrooms",
        FEATURE4: "Close to the city centre",
        FEATURE5: "#weeklyrent# PPPW",
        FEATURE6: "01/07/2025",
        FEATURE7: "2 Bathrooms",
        FEATURE8: "",
        FEATURE9: "",
        FEATURE10: "",
        SUMMARY:
          " Wonderfully presented five bedroom property. *Open plan living* *Equal size bedrooms* *Close to The University of Leeds* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          "Wonderfully presented five bedroom property.  *Open plan living* *Equal size bedrooms* *Close to The University of Leeds* * &pound;0.00PPPW* *01/07/2025* The property briefly comprises of five equal size bedrooms, spacious open plan living room and kitchen with white goods and 2 large house bathrooms with bath and shower. The house is located just a 5 minute walk to the university and very close to the city centre.  Woodhouse is the closest district to both The University of Leeds and Leeds Beckett University city centre campus and for this reason has become one of the most requested areas for students accommodation. It has several convenience stores, TJ&apos;s Bar and if your looking for a sweet treat then we definitely recommend Whitley&apos;s bakery! ",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "5",
        BATHROOMS: "1",
        LIVING_ROOMS: "0",
        PRICE: "87",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Providence Avenue, Woodhouse, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "300",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000293_0001.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_293_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "54",
        EPC_EERP: "84",
        EPC_EIR: "44",
        EPC_EIRP: "81",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
      {
        _id: "672c1945473342b86ffdb74b",
        AGENT_REF: "115_348r",
        ADDRESS_1: "3",
        ADDRESS_2: "Branksome Place",
        ADDRESS_3: "Hyde Park",
        TOWN: "Leeds",
        POSTCODE1: "LS6",
        POSTCODE2: "1RQ",
        FEATURE1: "EPC-D",
        FEATURE2: "Large living room",
        FEATURE3: "Big kitchen",
        FEATURE4: "Equal bedrooms",
        FEATURE5: "#weeklyrent# PPPW",
        FEATURE6: "Good size bedrooms",
        FEATURE7: "Central Hyde park",
        FEATURE8: "Central Hyde park",
        FEATURE9: "01/07/2025",
        FEATURE10: "",
        SUMMARY:
          " This is a wonderfully presented four bedroom property in the heart of Hyde Park. *Big living room* *Large kitchen* *Good size bedrooms* * &pound;0.00PPPW* *01/07/2025*",
        DESCRIPTION:
          " This is a wonderfully presented four bedroom property in the heart of Hyde Park. *Big living room* *Large kitchen* *Good size bedrooms* * &pound;0.00PPPW* *01/07/2025* This house briefly comprises of 4 equal sized double bedrooms. A great size kitchen diner with washer, dryer and gas hobs. The living room is just as large with leather sofas. The property has 1 bathroom and has the added area of an unused basement, perfect for storage. Hyde Park has the largest student population in Leeds as it is a short walk to both The University of Leeds and Leeds Beckett University city centre campus as well as many other institution&apos;s including Leeds College of Art and Design. It has several convenience stores, a continental supermarket, a picture house, bars and pubs including the legendary Brudenell Social club. On a warm day its residents flood to Woodhouse Moor to enjoy the sun!",
        BRANCH_ID: "115",
        STATUS_ID: "5",
        BEDROOMS: "4",
        BATHROOMS: "1",
        LIVING_ROOMS: "1",
        PRICE: "94",
        PRICE_QUALIFIER: "0",
        PROP_SUB_ID: "1",
        CREATE_DATE: "",
        UPDATE_DATE: "",
        DISPLAY_ADDRESS: "Branksome Place, Hyde Park, Leeds",
        PUBLISHED_FLAG: "1",
        LET_DATE_AVAILABLE: "2025-07-01",
        LET_BOND: "250",
        LET_TYPE_ID: "3",
        LET_FURN_ID: "0",
        LET_RENT_FREQUENCY: "5",
        LET_WASHING_MACHINE_FLAG: "Y",
        LET_DISHWASHER_FLAG: "N",
        LET_BURGLAR_ALARM_FLAG: "Y",
        LET_BILL_INC_WATER: "N",
        LET_BILL_INC_GAS: "N",
        LET_BILL_INC_ELECTRICITY: "N",
        LET_BILL_INC_TV_LICENCE: "N",
        LET_BILL_INC_TV_SUBSCRIPTION: "N",
        LET_BILL_INC_INTERNET: "N",
        TENURE_TYPE_ID: "1",
        TRANS_TYPE_ID: "2",
        NEW_HOME_FLAG: "0",
        MEDIA_IMAGE_00: "",
        MEDIA_IMAGE_01: "p000348_0024.jpg",
        MEDIA_IMAGE_TEXT_01: "",
        MEDIA_IMAGE_02: "p000348_0018.jpg",
        MEDIA_IMAGE_TEXT_02: "",
        MEDIA_IMAGE_03: "p000348_0019.jpg",
        MEDIA_IMAGE_TEXT_03: "",
        MEDIA_IMAGE_04: "p000348_0020.jpg",
        MEDIA_IMAGE_TEXT_04: "",
        MEDIA_IMAGE_05: "p000348_0021.jpg",
        MEDIA_IMAGE_TEXT_05: "",
        MEDIA_IMAGE_06: "p000348_0016.jpg",
        MEDIA_IMAGE_TEXT_06: "",
        MEDIA_IMAGE_07: "p000348_0017.jpg",
        MEDIA_IMAGE_TEXT_07: "",
        MEDIA_IMAGE_08: "p000348_0022.jpg",
        MEDIA_IMAGE_TEXT_08: "",
        MEDIA_IMAGE_09: "",
        MEDIA_IMAGE_TEXT_09: "",
        MEDIA_IMAGE_10: "",
        MEDIA_IMAGE_TEXT_10: "",
        MEDIA_IMAGE_11: "",
        MEDIA_IMAGE_TEXT_11: "",
        MEDIA_IMAGE_12: "",
        MEDIA_IMAGE_TEXT_12: "",
        MEDIA_IMAGE_13: "",
        MEDIA_IMAGE_TEXT_13: "",
        MEDIA_IMAGE_14: "",
        MEDIA_IMAGE_TEXT_14: "",
        MEDIA_IMAGE_15: "",
        MEDIA_IMAGE_TEXT_15: "",
        MEDIA_IMAGE_16: "",
        MEDIA_IMAGE_TEXT_16: "",
        MEDIA_IMAGE_60: "115_348_IMG_60.jpg",
        MEDIA_IMAGE_TEXT_60: "EPC",
        MEDIA_IMAGE_61: "",
        MEDIA_IMAGE_TEXT_61: "",
        MEDIA_FLOOR_PLAN_00: "",
        MEDIA_FLOOR_PLAN_TEXT_00: "",
        MEDIA_FLOOR_PLAN_01: "",
        MEDIA_FLOOR_PLAN_TEXT_01: "",
        UNIPOL_STANDARD: "1",
        PROPERTY_WEEK: "0",
        TENANT_TYPE: "0",
        FEED_SLIDE_01: "0",
        FEED_SLIDE_02: "0",
        FEED_SLIDE_03: "0",
        FEED_SLIDE_04: "0",
        FEED_SLIDE_05: "0",
        FEED_SLIDE_06: "0",
        FEED_SLIDE_07: "0",
        FEED_SLIDE_08: "0",
        FEED_SLIDE_09: "0",
        FEED_SLIDE_10: "0",
        FEED_SLIDE_11: "0",
        FEED_SLIDE_12: "0",
        FEED_SLIDE_13: "0",
        FEED_SLIDE_14: "0",
        FEED_SLIDE_15: "0",
        FEED_SLIDE_16: "0",
        MAIN_VIEWER: "0",
        EPC_EER: "60",
        EPC_EERP: "86",
        EPC_EIR: "53",
        EPC_EIRP: "84",
        TLS_INCENTIVE: "",
        TLS_SOCIALMEDIA: "",
        "~": "~",
        __v: 0,
      },
    ]);
  } catch (error) {
    console.log(error);
    res.status(403).json({ message: "Something went wrong" });
  }
});

propertyRouter.get("/page-count", async (req, res) => {
  try {
    const query = req.query;

    // Controlling filter
    const filter = {};
    if (query.agent_ref) {
      filter.AGENT_REF = new RegExp(query.agent_ref, "i");
    }
    if (query.badrooms && query.badrooms !== "0") {
      const bedroomsArray = query.badrooms.split(",").map(Number); // Convert the "4,5,7,8" string into an array of numbers
      filter.BEDROOMS = { $in: bedroomsArray };
    }
    if (query.max_price || query.min_price) {
      filter.$expr = {
        $and: [
          { $gte: [{ $toDouble: "$PRICE" }, Number(query.min_price)] },
          {
            $lte: [
              { $toDouble: "$PRICE" },
              query.max_price === "0" ? 2000 : Number(query.max_price),
            ],
          },
        ],
      };
    }
    if (query.prop_sub_id && query.prop_sub_id !== "") {
      filter.PROP_SUB_ID = query.prop_sub_id;
    }
    if (query.location && query.location !== "") {
      filter.$or = [
        { ADDRESS_2: new RegExp(query.location, "i") },
        { ADDRESS_3: new RegExp(query.location, "i") },
      ];
    }
    // Controlling pagination
    const itemsPerPage = 10;
    let skipCount = 0;
    if (query.selectedPage) {
      skipCount = (query.selectedPage - 1) * itemsPerPage;
    }
    const properties = await PropertyModel.find(filter).countDocuments();
    // const properties = await PropertyModel.countDocuments();
    res.send({ count: Math.ceil(properties / 10) });
  } catch (error) {
    console.log(error);
    res.status(403).send({ message: "Something went wrong" });
  }
});

propertyRouter.get("/:id", async (req, res) => {
  try {
    const { id } = req.params;
    const properties = await PropertyModel.findById(new ObjectId(id));
    return res.send(properties);
  } catch (error) {
    console.log(error);
    return res.status(403).json({ message: "Something went wrong" });
  }
});

module.exports = propertyRouter;
// export default propertyRouter;
